---
title: "432 Final Project Markdown"
author: "Clarisa Griffin"
date: "2025-03-30"
output: html_document
---

Github Link: https://github.com/CEGriffin/432-Final-Project

Group members: Clarisa Griffin (20270784), Emilia Gillette (20204160)

__Data Manipulation__

__Non-Normalized Data__
```{r, warning=F, message=F}
#load libraries
library(dplyr)
library(tidyverse)
library(tidyr)
library(ggplot2)

#load data
data<-read.csv("DataSynthesis.csv") #DataSynthesis.csv is pulled from Colautti et al., 2023

#separate out tag info into different lines

#create new columns to be turned into different aspects of the plant ID
#rename family to population, because theres another column that will actually eb the family
#remove un-needed columns
data<-data%>%
  rename(population=Family)%>%
  mutate(petri_dish=Tag) %>%
  mutate(family=Tag) %>%
  mutate(common_garden=Tag)%>%
  select(c("Tag", "petri_dish", "population", "family", "common_garden", "ID", starts_with("gh"), ends_with("Field"), starts_with("GM"), ends_with("Bolt"), starts_with("Chlor"), ends_with("Conc"), starts_with("RGR")), -c("GM_Fecundity", ends_with("Initial"), "GM_Leaf_Number"))

#use regular expressions to replace each plant ID column  with only the aspect of the ID needed
data$petri_dish<-sub("(\\w?).+","\\1", data$petri_dish)
data$family<-sub("\\w?\\|\\w+-([A-z0-9-]+)\\|.*", "\\1", data$family)
data$common_garden<-sub("\\w?\\|.+\\|(\\w)\\|.+", "\\1", data$common_garden)

#remove maple observations (we are only interested in garlic mustard)
data<-subset(data, population!="maple")

#remove observations for which there is no common garden data
unique(data$common_garden)
data<-subset(data, common_garden!="e|JBCHY1-1-50|?")
data<-subset(data, common_garden!="b|WSSWM3-1-0|?|?")
data<-subset(data, common_garden!="i163_2")

#Ensure columns are the right data class
#str(data)
data$Tag<-as.factor(data$Tag)
data$petri_dish<-as.factor(data$petri_dish)
data$population<-as.factor(data$population)
data$family<-as.factor(data$family)
data$common_garden<-as.factor(data$common_garden)
data$ID<-as.factor(data$ID)

#impute missing data by replacing NA with the mean of the column for numerical variables
#"bolt" data will be done later- needs further manipulation
data<-data%>%
  mutate(RGR1=ifelse(is.na(RGR1),mean(data$RGR1, na.rm=T),RGR1),
         RGR2=ifelse(is.na(RGR2),mean(data$RGR2, na.rm=T),RGR2),
         RGR3=ifelse(is.na(RGR3),mean(data$RGR3, na.rm=T),RGR3),
         RGR4=ifelse(is.na(RGR4),mean(data$RGR4, na.rm=T),RGR4),
         ChlorA=ifelse(is.na(ChlorA),mean(data$ChlorA, na.rm=T),ChlorA),
         ChlorB=ifelse(is.na(ChlorB),mean(data$ChlorB, na.rm=T),ChlorB),
         gluc_Conc=ifelse(is.na(gluc_Conc),mean(data$gluc_Conc, na.rm=T),gluc_Conc),
         flav_Conc=ifelse(is.na(flav_Conc),mean(data$flav_Conc, na.rm=T),flav_Conc),
         GM_Leaf_Len=ifelse(is.na(GM_Leaf_Len),mean(data$GM_Leaf_Len, na.rm=T),GM_Leaf_Len),
         GM_Leaf_Wid=ifelse(is.na(GM_Leaf_Wid),mean(data$GM_Leaf_Wid, na.rm=T),GM_Leaf_Wid),
         GM_TotalLeaf_Area =ifelse(is.na(GM_TotalLeaf_Area),mean(data$GM_TotalLeaf_Area, na.rm=T),GM_TotalLeaf_Area),
         GM_NumberOfLeaves =ifelse(is.na(GM_NumberOfLeaves),mean(data$GM_NumberOfLeaves, na.rm=T),GM_NumberOfLeaves)
)

#create mortality column out of "bolt" data
#most of the bolt columns are "dead", will have to do analysis based on just mortality, then again with living bolt data
data<-data%>%
  mutate(mortality=Larg_Leaf_Len_Bolt)

data$mortality<-sub("\\d+","1", data$mortality)
data$mortality<-sub("Dead","0", data$mortality)

#separate out bolt data
bolt_data<-subset(data, Larg_Leaf_Len_Bolt!="Dead")

#Ensure columns are the right data class
bolt_data$Larg_Leaf_Len_Bolt<-as.numeric(bolt_data$Larg_Leaf_Len_Bolt)
bolt_data$Larg_Leaf_Wid_Bolt<-as.numeric(bolt_data$Larg_Leaf_Wid_Bolt)
bolt_data$GM_StemHeight_Bolt<-as.numeric(bolt_data$GM_StemHeight_Bolt)
bolt_data$GM_Leaf_Number_Bolt<-as.numeric(bolt_data$GM_Leaf_Number_Bolt)

#impute NAs
bolt_data<-bolt_data%>%
  mutate(Larg_Leaf_Len_Bolt=ifelse(is.na(Larg_Leaf_Len_Bolt),mean(data$Larg_Leaf_Len_Bolt, na.rm=T),Larg_Leaf_Len_Bolt),
         Larg_Leaf_Wid_Bolt=ifelse(is.na(Larg_Leaf_Wid_Bolt),mean(data$Larg_Leaf_Wid_Bolt, na.rm=T),Larg_Leaf_Wid_Bolt),
         GM_StemHeight_Bolt=ifelse(is.na(GM_StemHeight_Bolt),mean(data$GM_StemHeight_Bolt, na.rm=T),GM_StemHeight_Bolt),
         GM_NumberOfLeaves=ifelse(is.na(GM_NumberOfLeaves),mean(data$GM_NumberOfLeaves, na.rm=T),GM_NumberOfLeaves))

#write files into a csv
write.csv(data, file="./raw_data.csv", row.names=F)
write.csv(bolt_data, file="./raw_bolt_data.csv", row.names=F)

```


__Normalized Data__
```{r, warning=F, message=F}
#Check normality of numerical variables with histogram
long_data<-pivot_longer(data, c(12:15, 20:27), names_to="metric", values_to="values")

ggplot(long_data, aes(x=values)) +
  geom_histogram() +
  theme_classic() +
  facet_wrap(~metric, scales="free")

#check for normality with qq plots
ggplot(long_data, aes(sample=values)) +
  geom_qq() +
  stat_qq_line() +
  facet_wrap(~metric, scales="free") #nothing looks too far from normal here, probably doesnt need any kind of normalization other than conversion to Z scores

#transform all numerical columns to z scores
data<-data%>%
  mutate(z_RGR1=(RGR1-mean(RGR1))/sd(RGR1),
         z_RGR2=(RGR2-mean(RGR2))/sd(RGR2),
         z_RGR3=(RGR3-mean(RGR3))/sd(RGR3),
         z_RGR4=(RGR4-mean(RGR4))/sd(RGR4),
         z_ChlorA=(ChlorA-mean(ChlorA))/sd(ChlorA),
         z_ChlorB=(ChlorB-mean(ChlorB))/sd(ChlorB),
         z_gluc_Conc=(gluc_Conc-mean(gluc_Conc))/sd(gluc_Conc),
         z_flav_Conc=(flav_Conc-mean(flav_Conc))/sd(flav_Conc),
         z_Leaf_Len=(GM_Leaf_Len-mean(GM_Leaf_Len))/sd(GM_Leaf_Len),
         z_Leaf_Wid=(GM_Leaf_Wid-mean(GM_Leaf_Wid))/sd(GM_Leaf_Wid),
         z_TotalLeaf_Area=(GM_TotalLeaf_Area-mean(GM_TotalLeaf_Area))/sd(GM_TotalLeaf_Area),
         z_NumberOfLeaves=(GM_NumberOfLeaves-mean(GM_NumberOfLeaves))/sd(GM_NumberOfLeaves))%>%
   select("Tag", "petri_dish", "population", "family", "common_garden", "ID", "gh_bench", "gh_col", "gh_row", "Row_Field", "Col_Field", starts_with("z_"), "mortality")

#how does it look after the transformation?
long_data<-pivot_longer(data, starts_with("z_"), names_to="metric", values_to="values")

ggplot(long_data, aes(x=values)) +
  geom_histogram() +
  theme_classic() +
  facet_wrap(~metric, scales="free")

#bolt data check for normality - needs log transformation
long_bolt_data<-pivot_longer(bolt_data, ends_with("Bolt"), names_to="metric", values_to="values")

ggplot(long_bolt_data, aes(x=values)) +
  geom_histogram() +
  theme_classic() +
  facet_wrap(~metric, scales="free")

#visualize with qq plot
ggplot(long_bolt_data, aes(sample=values)) +
  geom_qq() +
  stat_qq_line() +
  facet_wrap(~metric, scales="free") #also doesnt look too bad


#normalize bolt data and log transform
bolt_data<-bolt_data%>%
  mutate(Larg_Leaf_Len_Bolt=log(Larg_Leaf_Len_Bolt),
         Larg_Leaf_Wid_Bolt=log(Larg_Leaf_Wid_Bolt),
         GM_StemHeight_Bolt=log(GM_StemHeight_Bolt),
         GM_Leaf_Number_Bolt=log(GM_Leaf_Number_Bolt))%>%
  mutate(z_log_len_bolt=(Larg_Leaf_Len_Bolt-mean(Larg_Leaf_Len_Bolt))/sd(Larg_Leaf_Len_Bolt),
         z_log_wid_bolt=(Larg_Leaf_Wid_Bolt-mean(Larg_Leaf_Wid_Bolt))/sd(Larg_Leaf_Wid_Bolt),
         z_log_stemheight_bolt=(GM_StemHeight_Bolt-mean(GM_StemHeight_Bolt))/sd(GM_StemHeight_Bolt),
         z_log_leafnumber_bolt=(GM_Leaf_Number_Bolt-mean(GM_Leaf_Number_Bolt))/sd(GM_Leaf_Number_Bolt),
         z_RGR1=(RGR1-mean(RGR1))/sd(RGR1),
         z_RGR2=(RGR2-mean(RGR2))/sd(RGR2),
         z_RGR3=(RGR3-mean(RGR3))/sd(RGR3),
         z_RGR4=(RGR4-mean(RGR4))/sd(RGR4),
         z_ChlorA=(ChlorA-mean(ChlorA))/sd(ChlorA),
         z_ChlorB=(ChlorB-mean(ChlorB))/sd(ChlorB),
         z_gluc_Conc=(gluc_Conc-mean(gluc_Conc))/sd(gluc_Conc),
         z_flav_Conc=(flav_Conc-mean(flav_Conc))/sd(flav_Conc),
         z_Leaf_Len=(GM_Leaf_Len-mean(GM_Leaf_Len))/sd(GM_Leaf_Len),
         z_Leaf_Wid=(GM_Leaf_Wid-mean(GM_Leaf_Wid))/sd(GM_Leaf_Wid),
         z_TotalLeaf_Area=(GM_TotalLeaf_Area-mean(GM_TotalLeaf_Area))/sd(GM_TotalLeaf_Area),
         z_NumberOfLeaves=(GM_NumberOfLeaves-mean(GM_NumberOfLeaves))/sd(GM_NumberOfLeaves)) %>%
  select("Tag", "petri_dish", "population", "family", "common_garden", "ID", "gh_bench", "gh_col", "gh_row", "Row_Field", "Col_Field", starts_with("z_"), "mortality")


#check to see if the log transform did anything - looks much better
long_bolt_data<-pivot_longer(bolt_data, ends_with("bolt"), names_to="metric", values_to="values")

ggplot(long_bolt_data, aes(x=values)) +
  geom_histogram() +
  theme_classic() +
  facet_wrap(~metric, scales="free")

ggplot(long_bolt_data, aes(sample=values)) +
  geom_qq() +
  stat_qq_line() +
  facet_wrap(~metric, scales="free") #looks better

#write files into a csv
write.csv(data, file="./normalized_data.csv", row.names=F)
write.csv(bolt_data, file="./normalized_bolt_data.csv", row.names=F)
```

__Correlation Matrix__
```{r, warning=F, message=F}
#Load libraries
library(readr)
library(corrplot)
library(dplyr)

#Load in Data from GitHub 
MyData <- read.csv("raw_data.csv", header=T)
View(MyData)

#select only numeric variable columns
NumericDat<-MyData%>%
  select(c(12:15, 20:28))

#Creating correlation matrix 
CorMatrix <- cor(NumericDat, use = "pairwise.complete.obs")

# Plot the correlation matrix
corrplot(CorMatrix, method = "color", type = "upper", tl.cex = 0.8)

#Creating a table 
CorTable <- as.data.frame(CorMatrix)
print(CorTable)
```


__PCA__
```{r, warning=F, message=F, fig.height=5, fig.width=7}
#Load Libraries
library(dplyr)
library(ggplot2)

#Load data
pcaData<-read.csv("normalized_data.csv", header=T)

#select out the un-needed columns, leave columns with only data
pcaData_2<-pcaData %>%
  select(-c("Tag", "petri_dish", "population", "family", "ID",
            "gh_bench", "gh_col", "gh_row", "Row_Field", "Col_Field", "common_garden"))

#run PCA
plantPCA<-princomp(na.omit(pcaData_2),cor=F)

#checking the PCA output and its structure
#str(plantPCA)
#head(plantPCA)
#names(plantPCA)

#put PCA loadings into a data frame
PCloadings<-data.frame(Component=c(1:13),Eigenvalue=plantPCA$sdev^2)

#create a scree plot - elbow is around 5.0 principal components
ggplot(aes(x=Component,y=Eigenvalue),data=PCloadings) +geom_point() + geom_line()

#what are the loadings of each variable on the components 
#plantPCA$loadings

#combining the PCA with the original plant data for graphing 
plantCombined<-cbind(na.omit(pcaData), plantPCA$scores)

plantCombined<-plantCombined %>% 
  rename(PC1 = Comp.1, PC2 = Comp.2, PC3 = Comp.3, PC4= Comp.4, PC5 = Comp.5)

#make sure columns are the right data classes
#str(plantCombined)

plantCombined$population<-as.factor(plantCombined$population)

#creating the bivariate plots for PC1 vs PC2 
ggplot(aes(x=PC1,y=PC2,colour=population, shape=common_garden),data=plantCombined)+
  geom_point() + theme_bw()

ggplot(aes(x=PC2,y=PC3,colour=population, shape=common_garden),data=plantCombined)+
  geom_point() + theme_bw()

ggplot(aes(x=PC1,y=PC3,colour=population, shape=common_garden),data=plantCombined)+
  geom_point() + theme_bw()



#checking if the data exhibits the same trend when including growth data when plants are bolts

#load data
boltData<-read.csv("normalized_bolt_data.csv", header=T)

#select out un-needed columns, keep only numerical variables
pcaData2<-boltData %>%
  select(-c("Tag", "petri_dish", "population", "family", "ID",
            "gh_bench", "gh_col", "gh_row", "Row_Field", "Col_Field", 
            "common_garden"))

#make PCA
boltPCA<-princomp(pcaData2,cor=F)

#checking the PCA output and its structure
#str(boltPCA)
#head(boltPCA)
#names(boltPCA)

#put PCA loadings into a data frame
PCloadings2<-data.frame(Component=c(1:17),Eigenvalue=boltPCA$sdev^2)

#make a scree plot - elbow is around 5.0 principal components
ggplot(aes(x=Component,y=Eigenvalue),data=PCloadings2) +geom_point() + geom_line()

#what are the loadings of each variable on the components 
#boltPCA$loadings

#combining the PCA with the original plant data for graphing 
boltCombined<-cbind(boltData, boltPCA$scores)

boltCombined<-boltCombined %>% 
  rename(PC1 = Comp.1, PC2 = Comp.2, PC3 = Comp.3, PC4= Comp.4, PC5 = Comp.5, 
         PC6=Comp.6)

#str(boltCombined)

boltCombined$population<-as.factor(boltCombined$population)

#creating the bivariate plots for PC1 vs PC2, 2 vs 3, 1 vs 3
ggplot(aes(x=PC1,y=PC2,colour=population, shape=common_garden),data=boltCombined)+
  geom_point()+ theme_bw() 

ggplot(aes(x=PC2,y=PC3,colour=population, shape=common_garden),data=boltCombined)+
  geom_point()+ theme_bw()

ggplot(aes(x=PC1,y=PC3,colour=population, shape=common_garden),data=boltCombined)+
  geom_point()+ theme_bw()
```


__Decision tree__
```{r, warning=F, message=F}
#Load libraries
library(dplyr)
library(tree)

plantData<-read.csv("raw_data.csv", header=T)

## Not Down Sampled Decision Tree without Bolt Data

#Select out un-needed columns, use only columns with numerical data
plantDecide_raw<-plantData %>%
  select(-c("population", "ID", "gh_bench", "gh_col", "gh_row", 
            "Row_Field", "Col_Field", "petri_dish", "family", "Tag"))

#keeps only rows where common_garden is Q, N, or V
plantDecideQ<-subset(plantDecide_raw, common_garden == "Q")
plantDecideN<-subset(plantDecide_raw, common_garden == "N")
plantDecideV<-subset(plantDecide_raw, common_garden == "V")

plantDecide_raw<- rbind(plantDecideQ, plantDecideN, plantDecideV)

#select out bolt data
plantDecide<-plantDecide_raw %>%
  select(-c("Larg_Leaf_Len_Bolt", "Larg_Leaf_Wid_Bolt", "GM_StemHeight_Bolt", "GM_Leaf_Number_Bolt"))

#make sure columns ARE THE RIGHT DATA CLASSES
plantDecide$common_garden<-as.factor(plantDecide$common_garden)

#select out unneeded columns
plantTemp<- plantDecide %>%
  select(-c("common_garden"))

#create a matrix
plant_matrix<-as.matrix(plantTemp)

#checking covariance
#cov(plantTemp)

#separating into testing and training datasets
train<-c(1:nrow(plantDecide)) %% 2
plantTrain<-plantDecide[train == 1,]

test<-1-train
plantTest<-plantDecide[test == 1,]

#make a tree
plantTree<- tree(common_garden ~ ., data=plantTrain)

#plot the tree with text - these 2 following lines need to be run together
#plot(plantTree) 
#text(plantTree, cex =0.8)

#prune nodes
pruneTree<-cv.tree(plantTree, best=8, FUN=prune.tree)
plot(pruneTree) #run this and the next line together
text(pruneTree, cex=0.8)

#setting up confusion matrix
plantConfuse<-data.frame(Obs=plantTest$common_garden,Pred=predict(pruneTree, plantTest, type="class"))
table(plantConfuse)

#calculating the misclassification rate 
MisClass<-plantConfuse %>%
  filter(Obs!=Pred)
nrow(MisClass)/nrow(plantConfuse)

#checking that misclass and correct class = 1
correct<-plantConfuse %>%
  filter(Obs==Pred)
nrow(correct)/nrow(plantConfuse)

#sum does in fact equal 1

## Making a Decision tree with down sampling to account for fewer Vancouver samples
set.seed(100)
plantDecideQ2<-plantDecideQ[sample(nrow(plantDecideQ), 163),]

plantDecide2<-rbind(plantDecideQ2, plantDecideN, plantDecideV)

plantDecide2<-plantDecide2 %>%
  select(-c("Larg_Leaf_Len_Bolt", "Larg_Leaf_Wid_Bolt", "GM_StemHeight_Bolt", "GM_Leaf_Number_Bolt"))

plantDecide2$common_garden<-as.factor(plantDecide2$common_garden)

train2<-c(1:nrow(plantDecide2)) %% 2
plantTrain2<-plantDecide2[train2 == 1,]

test2<-1-train2
plantTest2<-plantDecide2[test2 == 1,]

plantTree2<-tree(common_garden ~ ., data=plantTrain2)

#plot the tree with text - run these 2 lines of code together
#plot(plantTree2) 
#text(plantTree2, cex =0.8)

#prune nodes
pruneTree2<-cv.tree(plantTree2, best=8, FUN=prune.tree)
plot(pruneTree2) #run this and the next line of code together
text(pruneTree2, cex=0.8)

#setting up confusion matrix
plantConfuse2<-data.frame(Obs=plantTest2$common_garden,Pred=predict(pruneTree2, plantTest2, type="class"))
table(plantConfuse2)

#calculating the misclassification rate 
MisClass2<-plantConfuse2 %>%
  filter(Obs!=Pred)
nrow(MisClass2)/nrow(plantConfuse2)

#checking that misclass and correct class = 1
correct2<-plantConfuse2 %>%
  filter(Obs==Pred)
nrow(correct2)/nrow(plantConfuse2)



## Making a Decision Tree with only plants that survived (mortality = 1) without down sampling
plantDecide3<-subset(plantDecide_raw, mortality == 1)

#ensures common garden is only Q, N or V
plantDecideQ_3<-subset(plantDecide3, common_garden == "Q")
plantDecideN_3<-subset(plantDecide3, common_garden == "N")
plantDecideV_3<-subset(plantDecide3, common_garden == "V")

plantDecide3<-rbind(plantDecideQ_3, plantDecideN_3, plantDecideV_3)

#make sure columns are the right characters classes
plantDecide3$common_garden<-as.factor(plantDecide3$common_garden)

#select out un needed columns
plantTemp2<- plantDecide3 %>%
  select(-c("common_garden", "mortality"))

#make sure columns are the right data classes
plantTemp2$Larg_Leaf_Len_Bolt <- as.numeric(plantTemp2$Larg_Leaf_Len_Bolt)
plantTemp2$Larg_Leaf_Wid_Bolt <- as.numeric(plantTemp2$Larg_Leaf_Wid_Bolt)
plantTemp2$GM_StemHeight_Bolt <- as.numeric(plantTemp2$GM_StemHeight_Bolt)
plantTemp2$GM_Leaf_Number_Bolt <- as.numeric(plantTemp2$GM_Leaf_Number_Bolt)

#str(plantTemp2)

#make a matrix
plant_matrix2<-as.matrix(plantTemp2)

plantDecide3<- plantDecide3 %>%
  select(-mortality)

#split training and testing data
train3<-c(1:nrow(plantDecide3)) %% 2
plantTrain3<-plantDecide3[train3 == 1,]

test3<-1-train3
plantTest3<-plantDecide3[test3 == 1,]

plantTree3<- tree(common_garden ~ ., data=plantTrain3)

#plot the tree with text
#plot(plantTree3) 
#text(plantTree3, cex =0.8)

#prune nodes
pruneTree3<-cv.tree(plantTree3, best=8, FUN=prune.tree)
plot(pruneTree3)
text(pruneTree3, cex=0.8)

#setting up confusion matrix
plantConfuse3<-data.frame(Obs=plantTest3$common_garden,Pred=predict(pruneTree3, plantTest3, type="class"))
table(plantConfuse3)

#calculating the misclassification rate 
MisClass3<-plantConfuse3 %>%
  filter(Obs!=Pred)
nrow(MisClass3)/nrow(plantConfuse3)

#checking that misclass and correct class = 1
correct3<-plantConfuse3 %>%
  filter(Obs==Pred)
nrow(correct3)/nrow(plantConfuse3)

## Making a Decision tree with down sampling to account for mortality == 1
set.seed(100)
plantDecideQ_4<-plantDecideQ_3[sample(nrow(plantDecideQ_3), 38),]

plantDecide4<-rbind(plantDecideQ_4, plantDecideN_3, plantDecideV_3)

plantDecide4$common_garden<-as.factor(plantDecide4$common_garden)

plantDecide4<- plantDecide4 %>%
  select(-mortality)

train4<-c(1:nrow(plantDecide4)) %% 2
plantTrain4<-plantDecide4[train4 == 1,]

test4<-1-train4
plantTest4<-plantDecide4[test4 == 1,]

plantTree4<- tree(common_garden ~ ., data=plantTrain4)

#plot the tree with text
#plot(plantTree4) 
#text(plantTree4, cex =0.8)

#setting up confusion matrix
plantConfuse4<-data.frame(Obs=plantTest4$common_garden,Pred=predict(plantTree4, plantTest4, type="class"))
table(plantConfuse4)

#calculating the misclassification rate 
MisClass4<-plantConfuse4 %>%
  filter(Obs!=Pred)
nrow(MisClass4)/nrow(plantConfuse4)

#checking that misclass and correct class = 1
correct4<-plantConfuse4 %>%
  filter(Obs==Pred)
nrow(correct4)/nrow(plantConfuse4)

```

__Cluster Tree__
```{r, warning=F, message=F}
#Create cluster tree to asses whether plants
#group by common garden or population

#load libraries
library(ggplot2)
library(ape)
library(reshape2)
library(viridis)
library(dplyr)
library(ggtree)

#load data
data<-read.csv("./normalized_data.csv", row.names=NULL)

#give data row names
uniq_name<-make.names(data$Tag, unique=T)
row.names(data)<-uniq_name

#Taking the mean values for each population for each measurement so we can discriminate at the population level
p<-data%>%
  group_by(population)%>%
  summarize(z_RGR1=mean(z_RGR1),
            z_RGR2=mean(z_RGR2),
            z_RGR3=mean(z_RGR3),
            z_RGR4=mean(z_RGR4),
            z_ChlorA=mean(z_ChlorA),
            z_ChlorB=mean(z_ChlorB),
            z_gluc_Conc=mean(z_gluc_Conc),
            z_flav_Conc=mean(z_flav_Conc),
            z_Leaf_Len=mean(z_Leaf_Len),
            z_Leaf_Wid=mean(z_Leaf_Wid),
            z_TotalLeaf_Area=mean(z_TotalLeaf_Area),
            z_NumberOfLeaves=mean(z_NumberOfLeaves))

#select out population
p2<-p %>%
  select(-c("population"))

#make p2 a data frame
p2<-data.frame(p2)

#give p2 row names
row.names(p2)<-p$population

#make a dataframe with only the important columns
data2<-data%>%
  select(starts_with("z_"))
#head(data2)

#make a distance matrix - this is a linear matrix by sample
distance<-dist(data2, method = "euclidean")
a<-as.matrix(distance)

distMrx<-melt(a)
names(distMrx)<-c("Query","Subject","Distance")

#distance matrix by population

distp<-dist(p2, method = "euclidean")
a2<-as.matrix(distp)

distMrx2<-melt(a2)
names(distMrx2)<-c("Query","Subject","Distance")

#visualize distances for population-level traits

ggplot(data = distMrx2, aes(x=Query, y=Subject, fill=Distance)) +
  geom_tile() +theme(axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0.5))+
  scale_fill_viridis(option="magma")

#tree building for sample-level, colour by population
tree1<-nj(distance)
#str(tree1)
#ggtree(tree1, layout="circular")

#extract population and common garden from the tags
pop<-gsub("^[a-z]\\.","",tree1$tip.label)
pop2<-sub("\\..*","",pop)
popGroups<-split(tree1$tip.label, pop2)
popCol<-groupOTU(tree1,popGroups)

ggtree(popCol,layout="circular",aes(colour=group), branch.length="none")
#ggtree(popCol,layout="rectangular",aes(colour=group))

#tree building for sample-level, colour by common garden
garden<-gsub(".*([QNV]).*","\\1",tree1$tip.label)
grep("b.WSSWM3.1.0....|e.JBCHY1.1.50..|e.JBCHY1.1.50...1", garden)
garden<-garden[-c(812,813,960)]

gardenGroups<-split(tree1$tip.label, garden)
gardenCol<-groupOTU(tree1,gardenGroups)

ggtree(gardenCol,layout="circular",aes(colour=as.factor(group)),branch.length = "none") +guides(color = guide_legend(title = "Common Garden")) + 
  scale_color_manual(values=c("blue", "red2", "green"))

#tree building for population-level trait
tree2<-nj(distp)
#str(tree2)
ggtree(tree2, layout="circular") + geom_tiplab(size=2,aes(angle=angle))
```


